name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Ex: v1.0.0

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set image name and tag
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/evolution-api
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            VERSION_TAG=main-${SHORT_SHA}
          fi
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION_TAG .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION_TAG
